### ISSUE TITLE
第2章Service 层抽取业务逻辑部分中段落缺少字

### ISSUE THREAD

**Issue by virgil66** [feiniaojin/Thinking-in-DDD#4]
**遇到的问题：**
在阅读第2章中Service 层抽取业务逻辑章节时，发现其中有一句话缺少字了，截图如下：
![Uploading WechatIMG14.jpg…]()
**期望结果**
将缺少的字补充完整

**Comment by feiniaojin** [comment]
系统提示:您的邮件被腾讯邮箱判定为垃圾邮件,请编辑后重新发送!

**Comment by feiniaojin** [comment]
收到，感谢您的积极反馈
